input_dir: G:/Test/in
output_dir: G:/Test/out
unknown_dir_name: unbekannt
tesseract_cmd: C:/Program Files/Tesseract-OCR/tesseract.exe
poppler_path: C:/poppler-25.07.0
tesseract_lang: deu+eng
use_ocr: true
use_ollama: false
ollama:
  host: http://localhost:11434
  model: llama3
dry_run: true
csv_log_path: logs/processed.csv
