input_dir: inbox
output_dir: processed
unknown_dir_name: unbekannt
tesseract_cmd: ''
poppler_path: ''
tesseract_lang: deu+eng
use_ocr: true
use_ollama: false
ollama:
  host: http://localhost:11434
  model: llama3
dry_run: false
csv_log_path: logs/processed.csv
output_filename_format: '{date}_{supplier}_{invoice_no}.pdf'
